project_id = "mmtdolqbdyzyfgakdyzo"

[functions.generate-image]
verify_jwt = false

[functions.edit-image]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.manage-roles]
verify_jwt = false

[functions.assign-admin]
verify_jwt = false